### ISSUE TITLE
bug: Can't use vite if you use the `@aws/amazon-ecs-plugin-for-backstage` package in your Backstage app

### ISSUE THREAD

**Issue by kissmikijr** [awslabs/backstage-plugins-for-aws#192]
### 📜 Description

I encountered this bug when I wanted to switch my bundler in my Backstage frontend application from webpack to vite: 

```
[0] ✘ [ERROR] Failed to resolve entry for package "@backstage/integration-aws-node". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

[0]   The plugin "vite:dep-pre-bundle" was triggered by this import
[0] 
[0]     ../../node_modules/@aws/amazon-ecs-plugin-for-backstage/node_modules/@aws/aws-core-plugin-for-backstage-common/dist/index.esm.js:3:45:
[0]       3 │ ...aultAwsCredentialsManager } from '@backstage/integration-aws-node';
```

Looks like the issue is because the package `@aws/aws-core-plugin-for-backstage-common` has a dependency towards the package `@backstage/integration-aws-node` which is a node-library package (which is a backend type of package) but because the `@aws/aws-core-plugin-for-backstage-common` is a common package it is used in the frontend package: [@aws/amazon-ecs-plugin-for-backstage](https://github.com/awslabs/backstage-plugins-for-aws/blob/main/plugins/ecs/frontend/package.json#L34) So ultimately the backend package ends up in the frontend bundle and the bundler fails. 

### 👍 Expected behavior

Cleanup the dependencies to not end up with backend code in the frontend plugins

### 👎 Actual Behavior with Screenshots

Right now some backend type of packages are getting bundled into the frontend and vite fails on them

### 👟 Reproduction steps

Add the plugin: `@aws/amazon-ecs-plugin-for-backstage` to your project's frontend package and try to start your frontend with the ` EXPERIMENTAL_VITE=1 ` flag

**Comment by niallthomson** [comment]
Hi @kissmikijr thanks for reporting this I'll take a look in to it

**Comment by niallthomson** [comment]
I think we'll need to split the `common` package and add a `node` package to resolve this. I'll try to figure out how much effort this will be this week.

**Comment by niallthomson** [comment]
I split the common package and published a new release. Can you let me know if this fixes the issue?

**Comment by niallthomson** [comment]
Closing this unless it comes back up
