### ISSUE TITLE
bug: Backwards incompatible annotations

### ISSUE THREAD

**Issue by drodil** [awslabs/backstage-plugins-for-aws#7]
### 📜 Description

The new plugins use new annotation fields for example `aws.amazon.com/aws-codebuild-project-arn` while in the `@aws/aws-codeservices-backend-plugin-for-backstage` this was `aws.amazon.com/aws-codebuild-project`. Updating to use the new plugins would require changes to existing `catalog-info.yaml` files which can be many. 

### 👍 Expected behavior

The new plugins should work also with the legacy annotation

### 👎 Actual Behavior with Screenshots

The new plugins do not work with the legacy annotation

### 👟 Reproduction steps

1. Update the plugins
2. Check some entity with old annotation

**Comment by niallthomson** [comment]
@drodil I think we can look to add backwards compatibility "temporarily" with an appropriate deprecation cycle.
