### ISSUE TITLE
bug: Tag annotation for the codepipeline plugin does not work

### ISSUE THREAD

**Issue by lvstb** [awslabs/backstage-plugins-for-aws#82]
### 📜 Description

When using the tag annotation for the codepipeline plugin, the card shows an error instead of the pipeline that i can show using the arn notation.

### 👍 Expected behavior

The pipeline overview should be shown.

### 👎 Actual Behavior with Screenshots

<img width="1434" alt="Screenshot 2024-04-18 at 10 49 51" src="https://github.com/awslabs/backstage-plugins-for-aws/assets/45992455/dce4a569-dce1-4fd3-9db6-2b1d7fd3d5b5">

### 👟 Reproduction steps

Use this tag annotation in the catalog-info: 
    aws.amazon.com/aws-codepipeline-tags: Stage=prod

### 🖥️ Your Environment

﻿﻿yarn backstage-cli info
OS:   Darwin 23.4.0 - darwin/arm64
node: v21.7.3
yarn: 4.1.1
cli:  0.25.2 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14, 0.6.1, 0.6.2
  @backstage/backend-common                                        0.17.0, 0.19.10, 0.20.2, 0.21.3, 0.21.5, 0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13, 0.6.15, 0.6.16
  @backstage/backend-tasks                                         0.5.18, 0.5.21, 0.5.20
  @backstage/catalog-client                                        1.6.0, 1.6.2, 1.6.3, 1.6.4
  @backstage/catalog-model                                         1.4.4, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3, 0.2.4
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2, 1.7.0
  @backstage/config                                                1.1.1, 1.2.0
  @backstage/core-app-api                                          1.12.0, 1.12.2, 1.12.3
  @backstage/core-compat-api                                       0.2.0, 0.2.2, 0.2.3, 0.2.4
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.0, 0.14.2, 0.14.3, 0.14.4
  @backstage/core-plugin-api                                       1.9.0, 1.9.1, 1.9.2
  @backstage/errors                                                1.2.3, 1.2.4
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0, 0.6.2, 0.6.3, 0.6.4
  @backstage/integration-aws-node                                  0.1.9, 0.1.11, 0.1.12
  @backstage/integration-react                                     1.1.24, 1.1.25, 1.1.26
  @backstage/integration                                           1.10.0, 1.9.0, 1.9.1
  @backstage/plugin-analytics-module-ga4                           0.1.8
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.10, 0.4.11, 0.4.8
  @backstage/plugin-bitbucket-cloud-common                         0.2.16
  @backstage/plugin-catalog-backend-module-aws                     0.3.7
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.1.28
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.11.0, 1.7.3, 1.10.0
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.17.0, 1.18.2
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-jenkins-backend                                0.3.7
  @backstage/plugin-jenkins-common                                 0.1.24
  @backstage/plugin-jenkins                                        0.9.5
  @backstage/plugin-kubernetes-common                              0.7.4
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.36
  @backstage/plugin-permission-common                              0.7.12, 0.7.13
  @backstage/plugin-permission-node                                0.7.24, 0.7.26, 0.7.27
  @backstage/plugin-permission-react                               0.4.20, 0.4.21, 0.4.22
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.37
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0, 1.5.1
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-elasticsearch            1.3.16
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10, 1.2.11
  @backstage/plugin-search-react                                   1.7.6, 1.7.9
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.1, 0.5.2, 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7, 1.0.8

**Comment by niallthomson** [comment]
@lvstb thanks for reporting this. I've moved most of my own manual testing to exclusively use the tag annotations so its odd this isn't working.

That error looks like its a bit cryptic, I guess due to minification. Is there any way you can reproduce this in a local dev environment that might provide more information?

**Comment by lvstb** [comment]
Hi,
I tried to run it locally and this is now the error i came up with:


<img width="1665" alt="Screenshot 2024-04-23 at 10 18 20" src="https://github.com/awslabs/backstage-plugins-for-aws/assets/45992455/01bffac6-663e-466d-8fe8-e4cdd7897889">

**Comment by niallthomson** [comment]
It looks like the plugins aren't handling missing resources properly. This is something I'll work on fixing.

Are you sure the tag query you have defined is returning the correct results? Is the CodePipeline in the same AWS account as Backstage?

**Comment by lvstb** [comment]
The tag is correct. I did the exact same query for the ecs which is working btw.
Im using this config:

`aws:
  locator:
    type: resourceTaggingApi
    resourceTaggingApi:
      # Add each additional AWS account you wish to search
      accounts:
        - xxxxx
        - xxxxxx
      regions:
        - eu-west-1
`
i would rather switch to the config related locator, but not sure how to.

**Comment by niallthomson** [comment]
I just published release for several packages which may help here.

Firstly the resourceTaggingApi locator didn't currently support multiple accounts, so if the CodePipeline was in a different account then it would fail to find it. This would only affect tag lookups not ARNs.

Secondly there is improved handling for annotations with no resource match so that would show up clearer.
